services:
  # --- Frontend (Next.js) ---
  web:
    build: ./web
    container_name: codesense-web
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - DATABASE_URL=postgresql://codesense:securepassword@postgres:5432/codesense_db
    depends_on:
      - api
      - postgres # <--- Wait for DB
    restart: always

  # --- Backend (FastAPI) ---
  api:
    build: ./backend_v2
    container_name: codesense-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://codesense:securepassword@postgres:5432/codesense_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - QDRANT_URL=http://qdrant:6333
      - PYTHONPATH=/app
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} 
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:5555"]
    depends_on:
      - redis
      - minio
      - qdrant
      - postgres

  # --- Background Worker ---
  worker:
    build:
      context: ./backend_v2
      dockerfile: worker.Dockerfile
    container_name: codesense-worker
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - MINIO_ENDPOINT=minio:9000
        - MINIO_ACCESS_KEY=minioadmin
        - MINIO_SECRET_KEY=minioadmin
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis

  # --- Database & Queue Infrastructure ---
  redis:
    image: redis:7-alpine
    container_name: codesense-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: codesense-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  qdrant:
    image: qdrant/qdrant
    container_name: codesense-qdrant
    ports:
      - "6333:6333"

  # --- NEW: PostgreSQL ---
  postgres:
    image: postgres:15-alpine
    container_name: codesense-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=codesense
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=codesense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: